export enum UserRole {
  ADMIN = 'ADMIN',
  OPERATOR = 'OPERATOR',
  VIEWER = 'VIEWER',
}

export enum JobStatus {
  QUEUED = 'QUEUED',
  SCHEDULED = 'SCHEDULED',
  CLAIMED = 'CLAIMED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  DEAD_LETTERED = 'DEAD_LETTERED',
}

export enum JobType {
  IMMEDIATE = 'IMMEDIATE',
  DELAYED = 'DELAYED',
  SCHEDULED = 'SCHEDULED',
  RECURRING = 'RECURRING',
  BATCH_PARENT = 'BATCH_PARENT',
  BATCH_CHILD = 'BATCH_CHILD',
  WORKFLOW_NODE = 'WORKFLOW_NODE',
}

export enum RetryStrategy {
  FIXED = 'FIXED',
  LINEAR = 'LINEAR',
  EXPONENTIAL = 'EXPONENTIAL',
}

export enum WorkerStatus {
  HEALTHY = 'HEALTHY',
  STALE = 'STALE',
  DEAD = 'DEAD',
}

export enum ExecutionStatus {
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  TIMED_OUT = 'TIMED_OUT',
  ABANDONED = 'ABANDONED',
}

export enum LogLevel {
  DEBUG = 'DEBUG',
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
}

export enum JobHandlerType {
  HTTP_WEBHOOK = 'HTTP_WEBHOOK',
  SHELL_COMMAND = 'SHELL_COMMAND',
  CUSTOM_COMPUTE = 'CUSTOM_COMPUTE',
  SAMPLE_EMAIL = 'SAMPLE_EMAIL',
  SAMPLE_REPORT = 'SAMPLE_REPORT',
}
